name: Build

on: [push]

jobs:
  build_android:
    name: Android Demo
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Setup NativeScript
      uses: hrueger/setup-nativescript@v1.0.0
    - name: Install dependencies in /src
      working-directory: src
      run: npm i
    - name: Install dependencies in /demo
      working-directory: demo
      run: npm i
    - name: Build Demo Android
      working-directory: src
      run: npm run build.demo.android
  build_angular_android:
    name: Android Angular Demo
    runs-on: [windows-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Setup NativeScript
      uses: hrueger/setup-nativescript@v1.0.0
    - name: Install dependencies in /src
      working-directory: src
      run: npm i
    - name: Install dependencies in /demo-angular
      working-directory: demo-angular
      run: npm i
    - name: Build Angular Demo Android
      working-directory: src
      run: npm run build.demo-angular.android
  build_ios:
    name: iOS Demo
    runs-on: [macos-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Setup NativeScript
      uses: hrueger/setup-nativescript@v1.0.0
    - name: Install dependencies in /src
      working-directory: src
      run: npm i
    - name: Install dependencies in /demo
      working-directory: demo
      run: npm i
    - name: Build Demo iOS
      working-directory: src
      run: npm run build.demo.ios
  build_angular_ios:
    name: iOS Angular Demo
    runs-on: [macos-latest]
    steps:
    - uses: actions/checkout@v1
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12
    - name: Setup NativeScript
      uses: hrueger/setup-nativescript@v1.0.0
    - name: Install dependencies in /src
      working-directory: src
      run: npm i
    - name: Install dependencies in /demo-angular
      working-directory: demo-angular
      run: npm i
    - name: Build Angular Demo iOS
      working-directory: src
      run: npm run build.demo-angular.ios